### ISSUE TITLE
Refresh the JWT token by using the refresh_token

### ISSUE THREAD

**Issue by codepfleger** [trasiercom/trasier-client#25]
See OAuthTokenSage.refreshToken

And schedule the refresh

  private final ScheduledExecutorService scheduler = getExitingScheduledExecutorService(
      new ScheduledThreadPoolExecutor(1));
    // Wake up every 10 seconds to check if access token has expired
    scheduler.scheduleAtFixedRate(this::refreshAccessToken, 10, 10, SECONDS);

**Comment by jlupi** [comment]
fixed on #hackergarten bern
